### ISSUE TITLE
Questions about the the Bounding Box Sequence and Ways to Annotate Them

### ISSUE THREAD

**Issue by AlonzoLeeeooo** [ysy31415/direct_a_video#4]
Hi @ysy31415 ,

Thanks so much for your amazing work! I wonder would you please share the ways how you annotate the bounding box sequence?

Besides, I've noticed that the given example bounding box sequence are float values within [0, 1]. Would you please illustrate how these values are projected to the ones of height and width? Or is there any available scripts for us to build the correlation?

Thank you so much in advance for your precious time and attention from your busy schedule. And looking forward to your reply!

Best regards

**Comment by ysy31415** [comment]
@AlonzoLeeeooo  Hi, thanks for your interest.

(1) For box annotating, I wrote a UI, where you can draw box trajectory on canvas, and click "save box sequence as .npy" button to save it as numpy arrays, as shown below:
![image](https://github.com/user-attachments/assets/00cb8f25-6701-4e27-bfcf-a9429e8b578a)

To launch the UI, you can run ./ui/main_ui.py on the machine that supports graphics display.


(2) I use normalized box value within [0,1] because this can adapt to different video sizes. The box sequence is n*4 array, where n is number of boxes, 4 means [x1,y1,x2,y2], the normalized coordinates (value range 0~1) of left-top and right-bottom corners in each frame. To convert it into actual coordinates, you can simply multiply them by [video_width, video_height, video_width, video_height], as shown here: https://github.com/ysy31415/direct_a_video/blob/fa3ff99076015a293bd026111c06e5544be1cc7f/utils.py#L184

Also, there's a utility function that can convert box into binary masks:
https://github.com/ysy31415/direct_a_video/blob/fa3ff99076015a293bd026111c06e5544be1cc7f/utils.py#L144

**Comment by AlonzoLeeeooo** [comment]
@ysy31415 Thanks so much for your detailed and quick response!
